### ISSUE TITLE
don't update account after switchChain

### ISSUE THREAD

**Issue by Jam-Guo** [web3-wallet/web3-wallet#23]
**Describe the bug**
After disconnecting the wallet, switching the chain and reconnecting, the `account` is not updated and the value is `undefined`

**To Reproduce**
1. Go to '[Minted-staging](https://msta-minted.crorc.co/)'
2. Click on 'Account Avatar', and disconnected wallet
3. Click `MetaMask` to change chain to another chain
4. Click 'Connect' to connect wallet
5. the status is still `disconnected`

**Expected behavior**
after switching chain and reconnecting, the status need be `connected`

**Screenshots**
![image](https://github.com/web3-wallet/web3-wallet/assets/105196795/c066921d-d1e6-4e36-9639-15fe21c8fe20)
we found those code that after `switchChain` don't update account, so the value is still undefined.

 - Package Version [2.4.0]
 - MetaMask [10.33.1]

**Comment by logan-xyz** [comment]
Thanks fro reporting this issue. i can reproduce it.
